---
# tasks file for nginx
- name: "Устанавливаю пакеты"
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - nginx
    - php-fpm
    - php-cgi

- name: "Перекидываю конфигурационные файлы nginx"
  copy:  
    src: /home/debian/galaxy/nginx/files/phpfpm.conf
    dest: /etc/nginx/sites-available/phpfpm.conf
    
- name: "Перекидываю конфигурацию сайта"
  copy:
    src: /home/debian/galaxy/nginx/files/index.php
    dest: /opt/nginx/ansible/

- name: "Добавляю симлинк"
  file:
    src: /etc/nginx/sites-available/phpfpm.conf
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    state: link
  notify:
  - Reload nginx
