---
# tasks file for dnsmasq
- name: "Устанавливаю dnsmasq"
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: "Запускаю сервис"
  service:
    name: dnsmasq
    state: started
