rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: node # To get metrics about guest os
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: blackbox-node # To get metrics about the exporter itself
    metrics_path: /metrics
    static_configs:
    - targets: ['blackbox-exporter:9115']

  - job_name: blackbox-lms.skillfactory.ru # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [lms.skillfactory.ru]
    static_configs:
    - targets: ['blackbox-exporter:9115']
