$script = <<-'SCRIPT'
apt-get update
apt-get install build-essential libreadline-dev zlib1g-dev -y
wget https://ftp.postgresql.org/pub/source/v8.4.0/postgresql-8.4.0.tar.gz
tar -xvf postgresql-8.4.0.tar.gz
rm postgresql-8.4.0.tar.gz
cd postgresql-8.4.0
./configure CFLAGS="-Wno-aggressive-loop-optimizations"
make
make install 
adduser --disabled-password --gecos "" postgres
mkdir /usr/local/pgsql/data && mkdir /var/log/postgres
chown postgres:postgres /usr/local/pgsql/data && chown postgres:postgres /var/log/postgres
su postgres -c "/usr/local/pgsql/bin/initdb -D /usr/local/pgsql/data"
su postgres -c "/usr/local/pgsql/bin/postgres -D /usr/local/pgsql/data >/var/log/postgres/logfile 2>&1 &"
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "SFlegacyVagrant"
  config.ssh.insert_key = false 
  config.vm.provision "shell", inline: $script
  
  #Если нужно красивое название в virtualbox:
  #config.vm.provider "virtualbox" do |vb|
  #  vb.name = "SFlegacyVagrant"
  #end

  #После запуска виртуалки из "бокса" vagrant не мог подключиться к ВМ с ошибкой "Warning: Authentication failure. Retrying"
  #Народ активно разбирается в топике: https://github.com/hashicorp/vagrant/issues/5186 , один из предлагаемых вариантов:
  #config.ssh.insert_key = false 
  #Попробовал добавить, но после выключения ВМ не стартует воообще с ошибкой: Код ошибки: E_FAIL (0x80004005)
  #Различные пляски с бубном не не помогли. Невозможность vagrant'а подключиться к импортированному "боксу" - меньшее из зол.
  #------------
  #upd 11.09.2021
  #Все таки запустил ВМ с config.ssh... с добавлением в virtualbox параметра type=headless, то есть говорим virtualbox'у не пытаться запускать GUI
end

