pipeline {
    agent any

    stages {
        stage('jenk') {
            when { changeset "*/Jenkinsfile" }
                steps {
                    echo 'Jenkinsfile changed'
            }
        }
        stage('sql_1') {
            when { changeset "module_b8/jenkins/Jenkinsfile.txt" }
                steps {
                    echo 'simpleselect changed'
            }
        }
        stage('sql_2') {
            when { changeset "*/module_b8/jenkins/Jenkinsfile.txt" }
                steps {
                    echo 'simpleselect changed'
            }
        }           
    }
}
