pipeline {
    agent any

    stages {
        stage('jenk') {
            when { changeset "*/Jenkinsfile" }
                steps {
                    echo 'Jenkinsfile changed'
            }
        }
        stage('sql_1') {
            when { changeset "**/simpleselect.txt" }
                steps {
                    echo 'simpleselect changed'
            }
        }
        stage('sql_2') {
            when { changeset "module_b8/**" }
                steps {
                    echo 'simpleselect changed'
            }
        }           
        stage('sql_3') {
            when { changeset "**/simpleselect*" }
                steps {
                    echo 'simpleselect changed'
            }
        }     
    }
}
