pipeline {
    agent any

    stages {
        stage('jenk') {
            when { changeset "**/Jenkinsfile" }
                steps {
                    echo 'Jenkinsfile changed'
            }
        }
        stage('sql') {
            when { changeset "**/simpleselect.txt" }
                steps {
                    echo 'simpleselect changed'
                    sh 'query="simpleselect.txt"'
                    sh 'echo $query'
            }
        }
    }
}
