---
- hosts: localhost 
  #gather_facts: true 
  become: yes
  tasks: 
      - name: "Создаю группу"
        group:
          name: superusers
          state: present

      - name: "Добавляю пользователей"
        user:
          name: "{{ item  }}"
          shell: /bin/bash
          group: superusers
        loop:
          - user2
          - user3

      - name: "Редачу Sudoers"
        lineinfile:
          path: /etc/sudoers
          state: present
          regexp: '^(%superusers\s+ALL\=)'
          insertbefore: '^\# See sudoers\(5\)' 
          line: '%superusers   ALL=(ALL:ALL) NOPASSWD: ALL'
          validate: /usr/sbin/visudo -cf %s
